### ISSUE TITLE
Build-in function `compile` redefined in `species` module

### ISSUE THREAD

**Issue by FanwangM** [theochem/AtomDB#109]
It is noticed that the build in `compile` function (https://docs.python.org/3/library/functions.html#compile) is redefined in https://github.com/theochem/AtomDB/blob/9c42c3641025ab533f3c3e678db7464756114fe0/atomdb/species.py#L715-L748
We should use a better name other than this. What name would you prefer? `compile_species()` or `compile_instance()`?  Thanks.

@PaulWAyers @marco-2023 @gabrielasd  @msricher

**Comment by PaulWAyers** [comment]
I have no strong preference but `compile_species` seems more specific to me.

**Comment by msricher** [comment]
I agree. I can't believe I never noticed this!

**Comment by FanwangM** [comment]
This is fixed in https://github.com/theochem/AtomDB/pull/118.
