### ISSUE TITLE
Update Tables in Documentation

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/AtomDB#125]
We need to update the table in the landing page of the documentation, because NIST does not provide local properties but HCI does. (things are shifted over by one column at the bottom of the table).

I'm wondering how we can easily express which atoms/ions are covered by which datasets. It would be good to have a very short description of which species are covered in each dataset, especially since only the `hci` dataset is actively changing.

**Comment by gabrielasd** [comment]
The first part of this issue has been addressed by commit 76fe3af06e0f94963f5a52ee0dc956a66ab46e56.
I'll close this issue and open a new one for the second requirement about including information about what species are covered by each dataset.
