### ISSUE TITLE
[Doc] Write Sphinx-Doc pages

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#13]
Fill out Sphinx documentation

* Installation
* Usage
* Library structure
* Datasets & Properties
* Contributing (how to add datasets!)
* API

**Comment by maximilianvz** [comment]
@PaulWAyers, during our meeting yesterday, you said you reserved a domain name for AtomDB. Could you please remind me of what this was?

**Comment by PaulWAyers** [comment]
Note that `atomdb.qcdevs.org` name is reserved.

**Comment by Aditish51** [comment]
Hello, @maximilianvz Is this issue resolved? Or is there something I can work upon related to this issue?

**Comment by PaulWAyers** [comment]
@Aditish51 the site is built at `https://atomdb.qcdevs.org/` . It still needs polish but that's something that will come naturally as we prepare for release in the next few weeks, I think.
