### ISSUE TITLE
Support promolecules with only one atom

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/AtomDB#134]
When a promolecule has only one atom, specified by an array with one fewer dimension than expected, we should still be able to build the pro-atom density (centered on a point of interest). I.e., it is a bit unpleasant that one has to do things like

`atomdb.make_promolecule(mol.atnums[i,np.newaxis], mol.atcoords[i, np.newaxis], dataset=dataset)`

**Comment by msricher** [comment]
Try this: https://github.com/theochem/AtomDB/pull/135 (branch promol_one_atom)
