### ISSUE TITLE
[Units] Consistent internal units

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#17]
Corresponding values/properties between raw datasets may be stored with different units (e.g. conceptual DFT properties [here](https://github.com/theochem/AtomDB/blob/master/atomdb/data/c6cp04533b1.csv) in eV  vs a.u. when computed from HCI/gaussian datasets). We should be consistent and convert them to an internal unit convention as was done in the old repo.

We are using the [units](https://github.com/theochem/AtomDB/blob/master/atomdb/units.py) module from there when parsing the mass and atomic radii parameters, so the compilation scripts could also import it.

Thes units cript should be updated to use `scipy.constants`:
https://docs.scipy.org/doc/scipy/reference/constants.html

(Likely this is affects mainly the [`nist`](https://github.com/theochem/AtomDB/blob/master/atomdb/datasets/nist/__init__.py) dataset)

**Comment by PaulWAyers** [comment]
I think it would be better to just use scipy constants directly. @FarnazH may disagree with me, as she's a coauthor on the`units` module, but the nomenclature there is confusing to me compared to just direct invocation of the appropriate conversion factor from `scipy.constants`.

**Comment by gabrielasd** [comment]
The class in the [periodic](https://github.com/theochem/AtomDB/blob/master/atomdb/periodic.py#L213) module
is replacing the function [get_element_data](https://github.com/theochem/AtomDB/blob/968ebf1e48de37af1dd3c20a67263184b66e24a7/atomdb/api.py#L458). Therefore, the conversion that `get_element_data` was doing from the original unit system in elements.csv to our internal units (atomic units) should be supported in `periodic` as well. The relevant lines in `get-element_data` are:
https://github.com/theochem/AtomDB/blob/968ebf1e48de37af1dd3c20a67263184b66e24a7/atomdb/api.py#L505-L520

An alternative would be to take care of this conversion in the compilation scripts instead, for example as it's done here for the [nist](https://github.com/theochem/AtomDB/blob/master/atomdb/datasets/nist/__init__.py) dataset:
https://github.com/theochem/AtomDB/blob/968ebf1e48de37af1dd3c20a67263184b66e24a7/atomdb/datasets/nist/__init__.py#L133

**Comment by gabrielasd** [comment]
With the changes introduced by PR #33 and #50 the current code compiles all data in internal units.
The definitions of the units can be found in the utility module:
https://github.com/theochem/AtomDB/blob/2121615031c8cf14a2a6f2531cda7bb45ce545f6/atomdb/utils.py#L239

I'll close this issue for now, in the future we may want to restore a units module.
