### ISSUE TITLE
GitHub Actions Testing Failing

### ISSUE THREAD

**Issue by maximilianvz** [theochem/AtomDB#26]
If you look at the "Actions" tab, you can see that the workflow for automatically running the test scripts upon opening a PR or pushing to master isn't quite working yet. The reason for this is the [periodic.py](https://github.com/theochem/AtomDB/blob/master/atomdb/periodic.py) module. Specifically, dictionaries entitled `num2Ar` and `sym2Ar` are referenced in [`__all__`](https://github.com/theochem/AtomDB/blob/1ddf7b6a2e834476f7d75c5604326895f2672c2d/atomdb/periodic.py#L100-L101), but aren't established anywhere else. This causes `test_gaussian.py` to throw an error, and thus the whole GitHub Actions workflow fails. @gabrielasd, maybe you'd know more about how to handle this. Is it safe to delete `num2Ar` and `sym2Ar` here? I checked in my fork, and this allows the workflow to run successfully. However, you might still want to add these dictionaries to this module, so that may not be the best course of action.

**Comment by gabrielasd** [comment]
Hi @maximilianvz, yes, you can delete the module `periodic.py` or just comment/remove the lines that import its fruntions in the `__init__` file if its simpler:
https://github.com/theochem/AtomDB/blob/1ddf7b6a2e834476f7d75c5604326895f2672c2d/atomdb/__init__.py#L27

That module was borrowed from Grid and was added as a template here to be modified latter. 
@marco-2023 just to make sure, the functionality you are adding to parse the IUPAC data and other properties in the elements.csv does not rely in [periodic.py](https://github.com/theochem/AtomDB/blob/master/atomdb/periodic.py) right?

**Comment by maximilianvz** [comment]
@gabrielasd, thanks for the reply. I just pushed a commit to `master` in which I removed the `periodic.py` module and the line importing it in `atomdb/__init__.py`. If you check out the "Actions" tab now, you'll see that the tests run properly.

**Comment by gabrielasd** [comment]
@maximilianvz awesome, thanks for catching this problem!
