### ISSUE TITLE
Change Atom class to an Element class in periodic module

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#38]
Instead of [Atom](https://github.com/theochem/AtomDB/blob/968ebf1e48de37af1dd3c20a67263184b66e24a7/atomdb/periodic.py#L213) class, make an element class since the information of the elements table is only defined for the neutral species of the atom.
With this change one does not need to specify the charge as input.
Additionally, the column for the multiplicity should be removed since this information can be parsed from a separate table for multiplicities.

**Comment by marco-2023** [comment]
Done in PR #43
