### ISSUE TITLE
AtomDB  has iodata, grid, gbasis and pyci as dependencies.

### ISSUE THREAD

**Issue by marco-2023** [theochem/AtomDB#52]
In the actual code, when one of the data sets is imported, the  corresponding __init is loaded and several of them import iodata, gbasis etc. These are used in the compilation scripts (which are not needed for the common user of AtomDB). The problem is that because of these imports, AtomDB cannot be used without these dependencies.

I

**Comment by gabrielasd** [comment]
This issue was resolved by Marco by extracting the DB compilation function from the __init__ file inside each database folder.
