### ISSUE TITLE
Windows builds failing

### ISSUE THREAD

**Issue by msricher** [theochem/AtomDB#62]
Windows builds on Github Actions fail, I think because you can't install PySCF on Windows.

Proposed solution: Remove the Windows builds from Github Actions and don't support Windows. Most people use WSL for this kind of stuff now anyway.

Let me know what you all think and I'll update the .github/ folder.

**Comment by PaulWAyers** [comment]
I'm fine with this solution, but I'm forgetting why AtomDB has a dependence on PySCF? Is it a mandatory dependence? 

We should document cleanly that one needs to install Windows Subsystem for Linux. Probably link to Microsoft's documentation, 
https://learn.microsoft.com/en-us/windows/wsl/

**Comment by FanwangM** [comment]
The `PySCF` is used in https://github.com/theochem/AtomDB/blob/master/atomdb/datasets/uhf_augccpvdz/run.py, which caused problems for Windows. This is clearly documented in #105. Also, #105 fixes the failing windows pytest issue.
