### ISSUE TITLE
Missing mass values for elements 96-118

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#64]
The values for atomic mass we currently have are taken from the following source: https://doi.org/10.1515/pac-2019-0603 
However, in this reference the values for Tc, Pm, Po-Ac and Np-Og are missing.

**Comment by gabrielasd** [comment]
@PaulWAyers for Tc, Pm and Po-Ac I was taking the values from the column labelled Standard Atomic Weight in NIST site: https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl (which says is the average of the isotopic masses);
but this column is also empty for the elements with atomic number higher than 94.

Is it OK to take the values from the column Relative Atomic Mass for these other cases and just average them when there are multiple values?

**Comment by PaulWAyers** [comment]
Up to Pu it seems there is the data to have either the most abundant isotope or the isotopic average. In NIST notation, a single number in brackers [98] for Tc for example indicates that other isotopes are negligible. 

Beyond Pu, I guess we should use the isotope with the longest half-life. I checked and these are the following:
Z = 95 (Am) 243
Z=96 (Cm) 247
Z=97 (Bk) 247
Z = 98 (Cf) 251
Z= 101 (Md) 258

**Comment by PaulWAyers** [comment]
P.S. I would store both the isotopically averaged mass and the mass of the most common isotope (and set them equal when the isotopic average is not available). The most common isotope mass is the most frequently one used when looking at rovibrational spectroscopy, for example.
