### ISSUE TITLE
Fixing Jupyter Notebooks

### ISSUE THREAD

**Issue by maximilianvz** [theochem/AtomDB#70]
Hi, everyone. I'm trying to help out with improving/finalizing the API, and find it useful to start with the Jupyter Notebooks, ensuring that these work before moving forward. I've made some fixes, but also discovered where things don't really work. I took some time this afternoon to do this, and have made a branch in my forked version of the repo to easily show where I've had to adjust the repo's code to force things to work for me. This branch is located at: https://github.com/maximilianvz/AtomDB/tree/fix_notebooks

I have three commits thus far. The first one regarding the API changes should be self-explanatory and primarily fixes improper attribute naming in the notebooks. The other two are a bit more involved, and I think they are a consequence of a lack of uniformity when compiling datasets, so I'll explain things briefly below:

- [Workaround when only one mass stored](https://github.com/maximilianvz/AtomDB/commit/50110015c1d8bf0f1de43bab98e2c53e29db0af6): As described in the documentation for the `Species` class [here](https://github.com/theochem/AtomDB/blob/49162103a7131d5d449009b1be976189b8461015/atomdb/species.py#L363-L364), the `atmass` attribute is intended to be stored as a dictionary with two keys. However, in the `Promolecule_Tools.ipynb` notebook, the Beryillium atoms that get loaded to form the promolecule only have floats stored in the `atmass` attribute. You can test this by running `promol.atoms[0].atmass` in the second cell. If I don't include the change to the code in this commit, I'll get an error, "TypeError: 'float' object is not subscriptable." I'm not quite sure yet why the `atmass` values for Beryllium are floats, but, for example, that of the chlorine atom in the `Getting_Started.ipynb` notebook is a dictionary.
- [Workaround for uhf_augccpvdz dataset](https://github.com/maximilianvz/AtomDB/commit/0bf4baec83439f4787af3abd8bf2ae3e7f0f3125): In this commit, I made a few changes to two functions in `species.py`. The change to the `datafile` function involving `repodata.txt` fixes a simple problem where an underscore was accidentally included in the filename, which doesn't possess an underscore as it is stored on GitHub. The extra logic I added to the assignment of the `nexc` variable was necessary because file names in the `uhf_augccpvdz` are stored with the `nexc` variable as a single digit, not 3 digits - this is probably a problem with compiling the `uhf_augccpvdz` dataset. The same problem would occur for `charge` and `mult`, but these got passed as ellipses to the `datafile` function in the last cell of `Promolecule_Tools.ipynb`, so they didn't raise an error for that cell in the notebook (hence, I didn't make this same change for those variables). The changes I made regarding the `fields` dictionary in the `load` function had to be done because trying to initialize a `Species` object and passing a dictionary with the keys I excluded will raise an error because `self._data = SpeciesData(**fields)` isn't equipped to deal with those arguments (specifically, `dataset` is redundant, and `dispersion_C6` isn't set up). I don't know why the dictionary obtained via `unpackb(f.read(), object_hook=decode)` includes a `dataset` key for these `uhf_augccpvdz` files, because they don't for `slater` dataset files, for example (otherwise, the first cell in `Promolecule_Tools.ipynb` would break).

Hopefully, my notes above make sense. The changes I made to the code itself are certainly not good ways of going about fixing things. I should also note that an error owing to infinite values is raised in `Promolecule_NCI.ipynb`, which I didn't have time to look at yet, and may not possess the knowledge to deal with (others will probably be better able to do so). The first two notebooks seem to work now with the changes I made.

**Comment by gabrielasd** [comment]
@maximilianvz thank a lot for reporting these issues! There are definitely a few things we need to fix based on this.

I think the problems you found may be because the notebooks are using files from older database versions. With the notebooks updated to the new API and the DB version in [AtomDBdata](https://github.com/theochem/AtomDBdata), I'd expect there be no errors, but we'll have to check.
In any case, we need to remove these old Slater DB files from this repo to avoid confusion/errors.

**Comment by gabrielasd** [comment]
@maximilianvz the notebooks have been updated. Would you let me know if with the new versions the issues you found are resolved.

**Comment by gabrielasd** [comment]
I think the problems pointed out by @maximilianvz were solved after @marco-2023 updated the notebooks so I consider this issue solved.
