### ISSUE TITLE
[Database] Compilation and upload to repo

### ISSUE THREAD

**Issue by gabrielasd** [theochem/AtomDB#8]
Compiled datasets:
- [x] [nist](https://github.com/theochem/AtomDB/tree/master/atomdb/datasets/nist)
- [x] [slater](https://github.com/theochem/AtomDB/tree/master/atomdb/datasets/slater)
- [x] [numeric](https://github.com/theochem/AtomDB/tree/master/atomdb/datasets/numeric)
- [x] [gaussian](https://github.com/theochem/AtomDB/tree/master/atomdb/datasets/gaussian)
- [x] [hci](https://github.com/theochem/AtomDB/tree/master/atomdb/datasets/hci_augccpwcvqz)

**Comment by gabrielasd** [comment]
Hi @maximilianvz we are almost at the point where we just need to compile the database. Could I ask your help also with this? Maybe you could compile the `nist` or `numeric` datasets?
If yes, I can explain how to do it. Also, each dataset is a bit particular, and I don't think we have well established instructions to developer for how to do this, so feedback from experience is very useful.

**Comment by maximilianvz** [comment]
Sure, @gabrielasd, I'd be happy to take a shot at this. Let me know what you think the best way to explain the process is (i.e., GitHub, email, Zoom, etc.).

**Comment by gabrielasd** [comment]
Great! I'll open an issue for the `nist` dataset an describe the steps there. Thanks @maximilianvz
